pub const IDS: [&str; 65] = [
    "A1", "A2", "A3", "A8", "B4", "B5", "B6", "C7", "D9", "E10", "E11", "E12", "F13", "F14", "G15",
    "G16", "G17", "H18", "H19", "H20", "H21", "I23", "I24", "I25", "J26", "J27", "J28", "J29",
    "K30", "K31", "K32", "M36", "M37", "M38", "M39", "N40", "N41", "O42", "O43", "O44", "P45",
    "P46", "P47", "Q49", "Q50", "R52", "T55", "T56", "U57", "V58", "X59", "X61", "X62", "X63",
    "Y60", "Y64", "Y65", "Y66", "Y67", "Y68", "Y69", "Z91", "Z92", "Z93", "Z94",
];

pub const TITLES: [&str; 65] = [
    "Procedurell abstraktion",
    "Objektorienterad abstraktion",
    "Informationsgömning",
    "Gränssnitt mellan moduler",
    "Arv och subtypspolymorfism",
    "Liskov’s Substitution Principle",
    "Genomskärande åtaganden och arv",
    "Planering och uppföljning",
    "Dokumentation",
    "Implementera genericitet genom void-pekare",
    "Parametrisk polymorfism och typsäkerhet",
    "Designa med parametrisk polymorfism",
    "Iteration vs. rekursion",
    "Svansrekursion",
    "Aliasering",
    "Namn-baserad inkapsling",
    "Nästlade och inre klasser",
    "Jämförelsemetoden",
    "Skillnaden mellan identitet och ekvivalens",
    "Värdeöverföring",
    "Abstrakta klasser, metoder och interface",
    "Undantagshantering",
    "Olika metoder för felhantering",
    "Egendefinierade undantag",
    "Allokering på stacken vs. på heapen",
    "Manuell minneshantering",
    "Manuell vs. automatisk minneshantering",
    "Jämför två metoder för automatisk skräpsamling",
    "Gränssnitt mellan moduler",
    "Coupling & cohesion",
    "Separation of concerns",
    "C:s array-notation och pekararitmetik",
    "Använda pekare för att skapa länkade strukturer",
    "Värdeöverföring via pekare",
    "Pekare till pekare",
    "Kompilering, länkning och interpretering",
    "Bindning",
    "Profilering och optimering 1/3",
    "Profilering och optimering 2/3",
    "Profilering och optimering 3/3",
    "Gör en informell kodgranskning under fas 1",
    "Gör en informell kodgranskning under fas 2",
    "Åtgärda defekter efter en kodgranskning",
    "Enhetstestning",
    "Mät och resonera kring testkvalitet",
    "Debuggning med gdb",
    "Använda en utvecklingsmiljö på ett effektivt sätt",
    "Continuous Integration",
    "Byggverktyget Make",
    "Grundläggande terminalkommandon",
    "Essä",
    "Running Group Meetings Responsibly",
    "Kommunikation 1:1",
    "Kommuniktion 1:M",
    "Presentera projektet vid ett seminarium",
    "Använd en namngiven utvecklingsprocess och reflektera över utkomsten",
    "Skriv konsekvent bra kod",
    "Tillämpa kodgranskning löpande",
    "Delta aktivt i ett programmeringsprojekt",
    "Redovisa en fungerande projektuppgift",
    "Tillämpa testning under projektet",
    "Inlupp 1",
    "Inlupp 2",
    "Inlupp 3",
    "Inlupp 4",
];

pub const DEADLINES: [&str; 65] = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Dec 12, 2024",
    "",
    "Dec 16, 2024",
    "Sep 20, 2024",
    "Jan 14, 2025",
    "",
    "",
    "",
    "",
    "",
    "",
    "Oct 18, 2024",
    "Nov 15, 2024",
    "Dec 6, 2024",
    "Jan 16, 2025",
];

pub const DONE: [bool; 65] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
];

pub const PRESENT_SOON: [bool; 65] = [
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
    false, false, false, false, false, false, false, false, false, false, false, false, false,
];

pub const GRADES: [i8; 65] = [
    3, 3, 4, 4, 3, 4, 5, 3, 3, 3, 3, 4, 3, 4, 3, 3, 5, 3, 3, 4, 5, 3, 4, 4, 3, 3, 4, 5, 3, 4, 5, 3,
    3, 3, 4, 3, 4, 3, 4, 5, 3, 3, 4, 3, 4, 3, 3, 5, 3, 3, 4, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    4,
];

pub const PRESENTING_TYPES: [&str; 65] = [
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Studium",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Special",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab, Studium",
    "Lab, Studium",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
    "Lab, Studium",
    "Lab, Studium",
    "Special",
    "Special",
    "Special",
    "Special",
    "Special",
    "Report",
    "Report",
    "Report",
    "Report",
    "Report",
    "Report",
    "Lab",
    "Lab",
    "Lab",
    "Lab",
];

pub const PROGRAMMING_LANGUAGES: [&str; 65] = [
    "C", "Java", "C", "C", "Java", "Java", "Java", "C", "C", "C", "Java", "Java", "C", "C", "C",
    "Java", "Java", "Java", "Java", "C&Java", "Java", "Java", "C", "Java", "C", "C", "C&Java",
    "Java", "Java", "C", "C", "C", "C", "C", "C", "C&Java", "C&Java", "C/Java", "C/Java", "C/Java",
    "C", "C", "C", "C", "C", "C", "C/Java", "Git", "C", "Terminal", "Essä", "Möte", "C/Java",
    "Essä", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C",
];

pub const SPRINTS: [&str; 65] = [
    "Sprint 1", "Sprint 3", "Sprint 2", "Sprint 2", "Sprint 3", "Sprint 3", "Sprint 3", "Projekt",
    "Sprint 2", "Sprint 1", "Sprint 3", "Sprint 3", "Sprint 1", "Sprint 1", "Sprint 1", "Sprint 3",
    "Sprint 3", "Sprint 3", "Sprint 3", "Sprint 3", "Sprint 3", "Sprint 3", "Sprint 1", "Sprint 3",
    "Sprint 1", "Sprint 1", "Sprint 3", "Sprint 3", "Sprint 3", "Sprint 2", "Sprint 2", "Sprint 1",
    "Sprint 1", "Sprint 1", "Sprint 1", "Sprint 3", "Sprint 3", "Sprint 1", "Sprint 1", "Sprint 1",
    "Sprint 1", "Sprint 3", "Projekt", "Sprint 1", "Sprint 1", "Sprint 1", "Sprint 1", "Sprint 1",
    "Sprint 2", "Sprint 1", "Sprint 1", "IDK", "Sprint 1", "Sprint 1", "Projekt", "Projekt",
    "Projekt", "Projekt", "Projekt", "Projekt", "Projekt", "Sprint 1", "Sprint 2", "Sprint 3",
    "Sprint 4",
];

pub const COMMENTS: [&str; 65] = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Gärna under projekt",
    "Gärna under projekt",
    "Gärna under projekt",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Examineras via seminarium",
    "Kom till möten",
    "Lek TA",
    "Presentation till gruppen i forumet",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];
